### ISSUE TITLE
Integrate with clojure.test.check.clojure-test/defspec

### ISSUE THREAD

**Issue by DjebbZ** [bhb/expound#113]
Hi,

Just a feature idea. The output of `clojure.test.check.clojure-test/defspec` is a bit messy, maybe expound can do something about it ? Not sure it can/should, since the output shows you the first inputs that failed, then shrink them to minimal output that fails, so it's not directly related to a misused spec. But since expound humanize spec-related error messages, I thought maybe it could do for defspec too.

**Comment by bhb** [comment]
Thanks for suggesting this! I’ll think more about it and let you know.

**Comment by arichiardi** [comment]
I tried to hook up the printer before a call to `cljs.spec.test.alpha/check` but it seems nothing happens. Has anybody tried that?

**Comment by bhb** [comment]
@arichiardi I realize you've fixed the README in a PR (thanks!) but just for future readers of this issue: you need to call `explain-results` directly with the results from `check` (after setting the printer) e.g.

```clojure
(set! s/*explain-out* expound/printer)
(expound/explain-results (st/check `ranged-rand))
```

**Comment by bhb** [comment]
@DjebbZ Thanks again for submitting this!

After some thought, I've decided that this feature doesn't belong in Expound. Although `defspec` *can* be used in conjunction with spec, many people use `defspec` without spec at all. And you can use the generative testing features of spec without ever using `defspec`. 

I think that Expound should try to remain narrowly focused on printing spec errors. I'd be happy to see someone build a library that combines spec + expound + a new macro [like this](https://gist.github.com/kennyjwilli/8bf30478b8a2762d2d09baabc17e2f10#gistcomment-2682609) but I think it should be in a different library.

**Comment by DjebbZ** [comment]
Thanks for taking the time to think about it. I agree with you.

Keep rocking!
