### ISSUE TITLE
Using expound printer for `instrument` exceptions in the browser

### ISSUE THREAD

**Issue by mhuebert** [bhb/expound#152]
Recent updates in cljs [removed](https://github.com/clojure/clojurescript/commit/5f0fabc65ae7ba201b32cc513a1e5931a80a2bf7#diff-c62a39b0b4b1d81ebd2ed6b5d265e8cf) the `explain-out` string from exception messages. This means exceptions thrown by `instrument` will not contain a nicely formatted string even if all the instructions for setting up expound have been followed (eg. setting up `s/*explain-out*`). 

These changes to cljs were made with the intention that exceptions should contain only data, and leave formatting/printing to the edges of the system, eg. by a REPL. To help with this, we have the [cljs.repl/error->str](https://github.com/clojure/clojurescript/blob/4dfe78719bee33d44a058d9549ab98cde9e0b8fb/src/main/cljs/cljs/repl.cljs#L234) function, which handles printing of exceptions in a general way (not only spec errors).

What does this mean for the browser? Well, to start, we'll find that exceptions have become less informative than they used to be, until we  somehow leverage these new tools to make them meaningful again. There may be numerous approaches to this, each with their own tradeoffs.

a couple of approaches to consider:

1. print all uncaught exceptions using `repl/error->str` using a global error handler:

```clj
(ns app.core 
  (:require [cljs.spec.alpha :as s]
            [expound.alpha :as expound]
            [cljs.repl :as repl]))

(set! s/*explain-out* expound/printer)

(defn error-handler [message url line column e]
  (js/console.error e)
  (print (repl/error->str e))
  true)

(set! (.-onerror js/window) error-handler)
```

2. extend the `ExceptionInfo` type to always rely on the repl `error->str` function, so that errors you print in your own try/catch blocks are also formatted:

```clj
(extend-type ExceptionInfo
  IPrintWithWriter
  (-pr-writer [o writer opts]
    (-write writer (repl/error->str o))))
```

3. augment the console itself to use `cljs.repl/error->str` to format errors - this would be the domain of tools like [cljs-devtools](https://github.com/binaryage/cljs-devtools) 

4. patch/extend tools to (optionally) include formatted messages in exceptions

**Comment by mhuebert** [comment]
re: (3), here's a snippet for adding a [custom formatter](https://docs.google.com/document/d/1FTascZXT9cxfetuPRT2eXPQKXui4nWFivUnS_335T3U/view) to the Chrome devtools console that will use `repl/error->str` to format any `ExceptionInfo` encountered:
```clj
(defonce _formatter
         (some-> js/window.devtoolsFormatters
                 (.unshift
                  #js{:header (fn [object config]
                                (when (instance? ExceptionInfo object)
                                  (let [message (repl/error->str object)]
                                    #js["span" (re-find #"[^\n]+" message)])))
                      :hasBody (constantly true)
                      :body (fn [object config]
                              #js["div" (repl/error->str object)])})))
```

**Comment by bhb** [comment]
@mhuebert Thanks for the write up and the code! I've included these instructions in the README and linked to this issue.
