### ISSUE TITLE
allow passing options map to expound/expound-str

### ISSUE THREAD

**Issue by aleksandersumowski** [bhb/expound#162]
currently both `expound`/`expound-str` pass empty opt maps to `printer-str`. It would be nice if it accepted additional arity with opts map passed. Happy to prepare a PR if you were willing to accept such change

**Comment by bhb** [comment]
@aleksandersumowski Great idea! I've actually implemented this and it will be in the [next version of Expound](https://github.com/bhb/expound/tree/next). Thanks for the idea!
