### ISSUE TITLE
Feature inquiry: a convenience function for validating a value against a spec

### ISSUE THREAD

**Issue by aviflax** [bhb/expound#214]
I feel like I’ve written variations on this fn across a bunch of projects:

```clojure
(defn valid?!
  [spec val error-prefix]
  (when-not (s/valid? spec val)
    (throw (ex-info (str error-prefix ": " (expound/expound-str spec val {:print-specs? false}))
                    (s/explain-data spec val)))))
```

so I’m wondering whether this, or something similar, might be a good idea to include in Expound?

I’d be happy to submit a PR, if so.

Thank you!

**Comment by bhb** [comment]
@aviflax Thanks for the idea, I appreciate it! 

At least for now, I'm going to keep Expound focused on just improving the spec error messages. This is method is useful, but I think it's a better fit for a separate library.

**Comment by aviflax** [comment]
Sure, that makes sense. Thanks for considering it and the gracious feedback!

**Comment by bhb** [comment]
@devurandom Nice!
