### ISSUE TITLE
Don't pack resources/public/index.html into the release jar

### ISSUE THREAD

**Issue by nathell** [bhb/expound#60]
I am using expound in development mode for my app, and due to the way my app's routes are implemented, expound's `index.html` takes precedence over my app in dev mode. 

It appears to be only useful for development of expound itself, therefore I think it should not be included in the release jars.

**Comment by bhb** [comment]
@nathell Thank you for reporting this! You're correct, it should not be included. I'll fix with the next release.

**Comment by bhb** [comment]
@nathell Thanks again for reporting this. The bug should be fixed in Expound 0.4.0.
