### ISSUE TITLE
Custom error messages for preds look weird

### ISSUE THREAD

**Issue by bhb** [bhb/expound#80]
```
(s/def ::resolve (s/or :function ::resolver-fn
                       :protocol ::resolver-type))
(s/def ::resolver-fn fn?)
(expound/def ::resolver-type #(satisfies? resolve/FieldResolver %) "implement the com.walmartlabs.lacina.resolve/FieldResolver protocol")

(s/explain ::schema/resolve {})
-- Spec failed --------------------

  {}

should satisfy

  fn?

or

implement the com.walmartlabs.lacina.resolve/FieldResolver protocol
```

Note that last line looks like it is not indented correctly. 

In some cases, we want custom error message to be all the way to the left though (this is current behavior):

```
(s/def :example/temp #{:hot :cold})  
(expound/expound :example/temp 1)
;;-- Spec failed --------------------
;;
;;  1
;;
;;should be one of: :cold, :hot

(expound/def :example/name string? "should be a string")
(expound/expound :example/name 1)
;;-- Spec failed --------------------
;;
;;  1
;;
;;should be a string
```

**Comment by hlship** [comment]
Thanks for adding this!

**Comment by bhb** [comment]
I thought about this quite a bit and I think adding this special case (indent a custom message, but only when it's in an 'or' and only when it's replacing a predicate) adds too much complexity to the code for too little benefit. It's unfortunate that the indentation doesn't look ideal in this case, but I think that the relative simplicity of the current rules is a net win. 

Closing for now.
