### ISSUE TITLE
consider making the `relevant specs` section optional

### ISSUE THREAD

**Issue by carocad** [bhb/expound#82]
As specs grow the failing part might be quite deep in the validation stack.

This creates some readability problems since the `relevant-specs` section becomes too large to be usable at all. See example below:

![screen shot 2018-04-03 at 10 53 50](https://user-images.githubusercontent.com/10408729/38239668-b3d109be-372d-11e8-9f0c-a84b873d3c9f.png)

I have a 21 inch screen (I think :D ) and even so I am not able to display the complete error without having to scroll around trying to find the errors. 

I propose two options that might help solve this:
- make `relevant specs` section optional and configurable when setting up the printer
- collapse irrelevant spec pieces into `...` and show only the key-predicate that failed

I think that expound already goes to great lengths to manage option 2 so I guess that would only leave option 1 😞 ? 

Hope it helps

**Comment by bhb** [comment]
@carocad Thanks for reporting this!

I agree, the "Relevant specs" section is very noisy right now.

> collapse irrelevant spec pieces into ... and show only the key-predicate that failed

I have some ideas about to compact this section. One idea is to omit parts of it, as you have suggested. I am also thinking about a format like the one show in [this video clip](https://www.youtube.com/watch?v=o75g9ZRoLaw) (the output of `syndoc`). Unfortunately, that will probably need to wait.

> make relevant specs section optional and configurable when setting up the printer

Good news 😄 ! This is available today:

```
(binding [s/*explain-out* (expound/custom-printer {:print-specs? false})]
  (s/explain my-spec my-data))
```

This option has not been documented properly, but I'm going to merge in some doc fixes soon to fix this.

Please give it a try and let me know what you think.

**Comment by carocad** [comment]
> I am also thinking about a format like the one show in this video clip (the output of syndoc). Unfortunately, that will probably need to wait.

It looks like a very interesting way of approaching the problem :) 

I think however that you should avoid trying to define `(yet)` another grammar language for displaying specs. I dont have a good proposal about it unfortunately, but in my experience creating mappings between two worlds always ends up with leaky abstractions and complications for the users.

**Comment by carocad** [comment]
yes using `:print-specs false` solved the issue :)

thanks for the info

**Comment by bhb** [comment]
@carocad Thanks for reporting this! Since there is an option to turn of relevant specs, I'm going to close this for now and continue to think about ways to make this section less verbose.
